name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'assets/**'
      - 'content/**'
      - 'data/**'
      - 'i18n/**'
      - 'layouts/**'
      - 'static/**'
      - 'themes/**'
      - 'hugo.*'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.140.2"
          extended: true

      - name: Build
        run: hugo --minify --buildDrafts=false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public

      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            📝 *Обновление блога!*
            
            ✅ *Сборка успешна.*

            *Автор изменений:* ${{ github.actor }}
            *Сообщение коммита:* ${{ github.event.head_commit.message }}
            *URL коммита:* [Смотреть изменения в GitHub](${{ github.event.head_commit.url }})

            *Ветка:* ${{ github.ref_name }}
            *Репозиторий:* https://github.com/${{ github.repository }}

            🚀 Сайт обновлён на GitHub Pages!
      
      - name: Notify Failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: https://github.com/${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ❌ *Ошибка при обновлении блога!*
            
            *Автор изменений:* ${{ github.actor }}
            *Сообщение коммита:* ${{ github.event.head_commit.message }}
            *URL коммита:* [Смотреть изменения в GitHub](${{ github.event.head_commit.url }})

            *Ветка:* ${{ github.ref_name }}
            *Репозиторий:* ${{ github.repository }}

            ⚠️ Проверьте журнал сборки и исправьте ошибки.


